services:
  - type: web
    name: zuhrstar-bot
    env: node
    buildCommand: npm install
    startCommand: node bot.js

  - type: web
    name: zuhrstar-landing
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
